name: B站自动签到主脚本

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间 08:00）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: 拉取代码仓库
      uses: actions/checkout@v3
      
    - name: 配置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: 执行B站签到脚本
      env:
        BILIBILI_CONFIGS: ${{ secrets.BILIBILI_CONFIGS }}
      run: |
        python bilibili_checkin.py
